### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/stylelint-config-bootstrap#1]
Ref: https://github.com/twbs/bootstrap/issues/27490

- [x] Create repo
- [x] Protect master branch
- [ ] ~~Create npm project~~
- [ ] ~~Give members of css team publish rights to npm~~
- [x] Copy the Bootstrap configuration to this repo

Edit: npm setup will be continued when everything works

**Comment by ntwb** [comment]
@MartijnCuppens @XhmikosR I'm not sure if you tried to use `stylelint-config-bootstrap` for this project, but I'm happy to transfer the repo https://github.com/ntwb/stylelint-config-bootstrap and any related https://www.npmjs.com/package/stylelint-config-bootstrap permissions (@mdo already has full ownership of that BTW) etc over to the Bootstrap team if you would like.

If you'd also just like a deprecated notice or something on https://github.com/ntwb/stylelint-config-bootstrap I'm happy to do that, or anything else.

**Comment by XhmikosR** [comment]
@ntwb: thanks for contacting us :)

I didn't know the history, but I figured it out after I tried accidentally to push v0.1.0 and npm didn't allow me :P

But since we can't rewrite history, I went ahead and created a new package and deprecated the old one.

Not sure how to proceed, ideally I didn't want `twbs` in the name but now it's done :/

**Comment by ntwb** [comment]
@XhmikosR Something like this maybe:

1. Rename this repo to `stylelint-config-bootstrap`
2. Un-deprecate `stylelint-config-bootstrap`
3. Deprecate `stylelint-config-twbs-bootstrap`

It looks like you've already got access to `stylelint-config-bootstrap`

**Comment by XhmikosR** [comment]
@ntwb: yeah but the the 0.1.0 tag won't match the 0.1.0 version published on npm.

**Comment by ntwb** [comment]
Easy enough to do a version bump at the same time...

**Comment by XhmikosR** [comment]
Yes of course but the current npm v0.1.0 for example will not match your tag.

**Comment by ntwb** [comment]
Happy to coordinate any version bumps, deprecating versions etc

Let me know what you want to do and we can plan a time that works for both of us and get it done 😄

**Comment by XhmikosR** [comment]
I appreciate it :) But that's what I've been telling you :P

We can't really change this situation, i.e. make your 0.1.0 version match our git tag because one cannot delete old versions it seems.

On the repo side, we can do anything, but it's npm that doesn't allow this.
